// <auto-generated />
using System;
using Football.Show.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Football.Show.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20190419100952_ModifiedIndex")]
    partial class ModifiedIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Football.Show.Entities.Category", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<bool>("IsMenu");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Slug");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Football.Show.Entities.Clip", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClipType");

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<int?>("LinkType");

                    b.Property<int?>("MatchId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Clips");
                });

            modelBuilder.Entity("Football.Show.Entities.CrawlLink", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BaseLink")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<int?>("Finished");

                    b.Property<int?>("FromPage");

                    b.Property<bool>("IsCircle");

                    b.Property<bool>("IsFinished");

                    b.Property<int?>("ToPage");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("CrawlLinks");
                });

            modelBuilder.Entity("Football.Show.Entities.Formation", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<bool>("IsSubstitution");

                    b.Property<int?>("MatchId");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<int?>("Number");

                    b.Property<int>("Type");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("Football.Show.Entities.ImageServer", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Patch")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("Port");

                    b.Property<string>("ServerFtp")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ServerName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ServerUrl")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdatedAt");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ImageServers");
                });

            modelBuilder.Entity("Football.Show.Entities.Match", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Away")
                        .HasMaxLength(100);

                    b.Property<string>("AwayManager")
                        .HasMaxLength(100);

                    b.Property<string>("AwayPersonScored")
                        .HasMaxLength(300);

                    b.Property<int?>("CategoryId");

                    b.Property<string>("Competition")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Home")
                        .HasMaxLength(100);

                    b.Property<string>("HomeManager")
                        .HasMaxLength(100);

                    b.Property<string>("HomePersonScored")
                        .HasMaxLength(300);

                    b.Property<string>("ImageName")
                        .HasMaxLength(300);

                    b.Property<int?>("ImageServerId");

                    b.Property<DateTime?>("MatchDate")
                        .IsRequired();

                    b.Property<string>("Referee")
                        .HasMaxLength(100);

                    b.Property<string>("Score")
                        .HasMaxLength(5);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Stadium")
                        .HasMaxLength(100);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageServerId");

                    b.HasIndex("Slug");

                    b.ToTable("Matchs");
                });

            modelBuilder.Entity("Football.Show.Entities.Substitution", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<int?>("FormationId");

                    b.Property<int?>("MatchId");

                    b.Property<int?>("Minutes");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<int?>("Number");

                    b.Property<int>("Type");

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("FormationId")
                        .IsUnique();

                    b.HasIndex("MatchId");

                    b.ToTable("Substitutions");
                });

            modelBuilder.Entity("Football.Show.Entities.Tag", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreatedAt");

                    b.Property<DateTime?>("DeletedAt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime?>("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("Slug");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Football.Show.Entities.TagAssignment", b =>
                {
                    b.Property<int>("MatchId");

                    b.Property<int>("TagId");

                    b.HasKey("MatchId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TagAssignments");
                });

            modelBuilder.Entity("Football.Show.Entities.Clip", b =>
                {
                    b.HasOne("Football.Show.Entities.Match", "Match")
                        .WithMany("Clips")
                        .HasForeignKey("MatchId");
                });

            modelBuilder.Entity("Football.Show.Entities.Formation", b =>
                {
                    b.HasOne("Football.Show.Entities.Match")
                        .WithMany("Formations")
                        .HasForeignKey("MatchId");
                });

            modelBuilder.Entity("Football.Show.Entities.Match", b =>
                {
                    b.HasOne("Football.Show.Entities.Category", "Category")
                        .WithMany("Matches")
                        .HasForeignKey("CategoryId");

                    b.HasOne("Football.Show.Entities.ImageServer", "ImageServer")
                        .WithMany("Matches")
                        .HasForeignKey("ImageServerId");
                });

            modelBuilder.Entity("Football.Show.Entities.Substitution", b =>
                {
                    b.HasOne("Football.Show.Entities.Formation", "Formation")
                        .WithOne("Substitution")
                        .HasForeignKey("Football.Show.Entities.Substitution", "FormationId");

                    b.HasOne("Football.Show.Entities.Match", "Match")
                        .WithMany("Substitutions")
                        .HasForeignKey("MatchId");
                });

            modelBuilder.Entity("Football.Show.Entities.TagAssignment", b =>
                {
                    b.HasOne("Football.Show.Entities.Match", "Match")
                        .WithMany("TagAssignments")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Football.Show.Entities.Tag", "Tag")
                        .WithMany("TagAssignments")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
